---
- hosts: all
  become: yes
  vars:
    - app_version: 0.0.1
  tasks:
    - name: install nginx
      apt: name=nginx-full state=present update_cache=yes cache_valid_time=3600
    
    - name: deploy app
      template: src=index.html.j2 dest=/var/www/html/index.nginx-debian.html
      
    - name: restart nginx
      service: name=nginx state=restarted
